import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="banking",passwd="bank123")
mycursor = mydb.cursor()
mycursor.execute("create database bank")
mytb=mysql.connector.connect(host="localhost",user="banking",passwd="bank123",database="bank")
mcursor = mytb.cursor()
mcursor.execute("create table account(name varchar(30) not null,account_number numeric(13) primary key, customer_id numeric(7), dob varchar(10) not null, address varchar(100) not null, phone_number numeric(10) not null, email_id varchar(30) not null, password varchar(20) not null,  opening_balance numeric(20) not null)")
mcursor.execute("create table amount(account_number numeric(13) primary key,name varchar(20) not null, balance numeric(20),loan_taken numeric(20),loan_given numeric(20))")
mcursor.execute("create table loan(g_ac numeric(20),t_ac numeric(20),interest numeric(3),sum numeric(20))")
mcursor.execute("create table dep(ac_no numeric(20),deposit numeric(20))")
mcursor.execute("create table withd(ac_no numeric(20),withdrawl numeric(20))")
mcursor.execute("create table transfer(d_ac numeric(20),c_ac numeric(20),amo numeric(20))")
mcursor.execute("create table loant(g_ac numeric(20),t_ac numeric(20),interest numeric(20),l_am numeric(20))")
mcursor.execute("create table loant2(g_ac numeric(20),t_ac numeric(20),l_pay numeric(20))")
mcursor.execute("create table interest(g_ac numeric(20),t_ac numeric(20),in_r numeric(20),in_amo numeric(20))")